### ISSUE TITLE
在项目使用出现这个异常，看hyperf注解使用跟源码也没问题，不明原因，求救

### ISSUE THREAD

**Issue by justin-mc-lai** [lphkxd/hyperf-validate#2]
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/hyperf/vendor/mzh/hyperf-validate/src/Annotations/RequestValidation.php on line 18。
环境 "hyperf/guzzle": "~1.1.0",
          "php": ">=7.2",
        "ext-swoole": ">=4.4",

```
use Mzh\Validate\Annotations\RequestValidation;

/**
 * @AutoController()
 */
class User extends AbstractController
{
    /**
     * @RequestValidation(mode="User",scene="login",filter=true,throw=true)
     */
    public function login(RequestInterface $request,Jwt $jwt)
    {
        $username = $request->input('username');
        $password = $request->input('password');
        $systemUser = SystemUser::query()->where("username",$username)->first();
        if (!$systemUser){
            return ApiOutput::fail("帐号不存在");
        }

        if (crypt($password) == $systemUser->password) {
            $userData = [
                'uid' => $systemUser->id,
                'username' => $systemUser->username,
            ];
            $token = (string)$jwt->getToken($userData);
            $info = [
                "token" => $token,
                "ttl" => 7200
            ];
            return ApiOutput::success($info);
        }else{
            return ApiOutput::fail("密码错误");
        }

        return ApiOutput::fail("登陆失败");
    }
}

```

**Comment by lphkxd** [comment]
PHP版本需要7.4以上的，稍等我更新下

**Comment by lphkxd** [comment]
> PHP Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/hyperf/vendor/mzh/hyperf-validate/src/Annotations/RequestValidation.php on line 18。
> 环境 "hyperf/guzzle": "~1.1.0",
> "php": ">=7.2",
> "ext-swoole": ">=4.4",
> 
> ```
> use Mzh\Validate\Annotations\RequestValidation;
> 
> /**
>  * @AutoController()
>  */
> class User extends AbstractController
> {
>     /**
>      * @RequestValidation(mode="User",scene="login",filter=true,throw=true)
>      */
>     public function login(RequestInterface $request,Jwt $jwt)
>     {
>         $username = $request->input('username');
>         $password = $request->input('password');
>         $systemUser = SystemUser::query()->where("username",$username)->first();
>         if (!$systemUser){
>             return ApiOutput::fail("帐号不存在");
>         }
> 
>         if (crypt($password) == $systemUser->password) {
>             $userData = [
>                 'uid' => $systemUser->id,
>                 'username' => $systemUser->username,
>             ];
>             $token = (string)$jwt->getToken($userData);
>             $info = [
>                 "token" => $token,
>                 "ttl" => 7200
>             ];
>             return ApiOutput::success($info);
>         }else{
>             return ApiOutput::fail("密码错误");
>         }
> 
>         return ApiOutput::fail("登陆失败");
>     }
> }
> ```

已处理

**Comment by justin-mc-lai** [comment]
谢谢，我刚刚解决要来关闭，哈哈，谢谢作者开源
