### ISSUE TITLE
场景验证器无效

### ISSUE THREAD

**Issue by sevendiscovery** [lphkxd/hyperf-validate#4]
`<?php
declare(strict_types=1);

namespace App\Validate;

use Mzh\Validate\Validate\Validate;

class AuthValidation extends Validate
{
    protected $rule = [
        'device'   => 'require|length:32',
        'platform' => 'require|lower|in:android,ios',
        'system'   => 'require',
        'version'  => 'require|number|length:5',
    ];

    protected $field = [
        'version' => 'APP版本',
    ];

    protected $scene = [
        'guest' => ['device', 'platform', 'system', 'version'],
    ];
}`

   /**
     * 游客访问
     * @RequestMapping(path="guest", methods="POST")
     * @RequestValidation(mode="Auth",scene="guest",filter=true,throw=true)
     */
    public function guest()
    {
    }

传递错误的数据进去，依然通过校验，使用scene不能直接使用rule的规则么？必须scene里面每个字段都要独立定义规则，这样好麻烦咦

**Comment by great-zh** [comment]
下午我考虑把这个加入进去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sevendiscovery"<notifications@github.com&gt;; 
发送时间: 2020年5月27日(星期三) 凌晨4:09
收件人: "great-zh/hyperf-validate"<hyperf-validate@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [great-zh/hyperf-validate] 场景验证器无效 (#4)





 
`<?php
 declare(strict_types=1);
 
namespace App\Validate;
 
use Mzh\Validate\Validate\Validate;
 
class AuthValidation extends Validate
 {
 /**
 * 验证规则
 * @var array
 */
 protected $rule = [
 'device'   =&gt; 'require|length:32',
 'platform' =&gt; 'require|lower|in:android,ios',
 'system'   =&gt; 'require',
 'version'  =&gt; 'require|number|length:5',
 ];
 /**  * 字段描述  * @var array  */ protected $field = [     'version' =&gt; 'APP版本', ]; /**  * 场景规则  * @var array  */ protected $scene = [     'guest' =&gt; ['device', 'platform', 'system', 'version'], ];  
}`
 
/** * 游客访问 * @RequestMapping(path="guest", methods="POST") * @RequestValidation(mode="Auth",scene="guest",filter=true,throw=true) */ public function guest() {}
 
传递错误的数据进去，依然通过校验，使用scene不能直接使用rule的规则么？必须scene里面每个字段都要独立定义规则，这样好麻烦咦

**Comment by great-zh** [comment]
已更新

**Comment by sevendiscovery** [comment]
么么哒😘
